global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 3h

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '8341243138:AAGu3-5VIBFHTxj5Uo8iXRe6Ee9I3m4genc'
        chat_id: 5377484616
        parse_mode: 'Markdown'
        message: |
          ğŸš¨ *Alert:* {{ .CommonLabels.alertname }}
          ğŸ“¦ *Instance:* {{ .CommonLabels.instance }}
          ğŸ”¥ *Status:* {{ .Status }}
          {{- if .CommonLabels.job }}
          âš™ï¸ *Job:* {{ .CommonLabels.job }}
          {{- end }}
          {{- if .CommonAnnotations.summary }}
          ğŸ§¾ *Summary:* {{ .CommonAnnotations.summary }}
          {{- end }}
          {{- if .CommonAnnotations.description }}
          ğŸ’¬ *Description:* {{ .CommonAnnotations.description }}
          {{- end }}
