services:
  mysql_inforadar:
    image: mysql:8.0
    container_name: mysql_inforadar
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ryban8991!
      MYSQL_DATABASE: inforadar
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - default

  mysql_exporter_inforadar:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter_inforadar
    restart: unless-stopped
    environment:
      - DATA_SOURCE_NAME=root:ryban8991!@(mysql_inforadar:3306)/
    ports:
      - "9104:9104"
    depends_on:
      - mysql_inforadar
    networks:
      - default

  prometheus_inforadar:
    image: prom/prometheus:latest
    container_name: prometheus_inforadar
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    depends_on:
      - mysql_exporter_inforadar
      - node_exporter_inforadar
      - cadvisor_inforadar
    networks:
      - default

  node_exporter_inforadar:
    image: prom/node-exporter:latest
    container_name: node_exporter_inforadar
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - default

  cadvisor_inforadar:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor_inforadar
    restart: unless-stopped
    ports:
      - "8085:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - default

  loki_inforadar:
    image: grafana/loki:2.9.0
    container_name: loki_inforadar
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default

  promtail_inforadar:
    image: grafana/promtail:2.9.0
    container_name: promtail_inforadar
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"
    networks:
      - default

  grafana_inforadar:
    image: grafana/grafana:latest
    container_name: grafana_inforadar
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - prometheus_inforadar
      - loki_inforadar
    networks:
      - default

  inforadar_ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inforadar_ui
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mysql_inforadar
    networks:
      - default

networks:
  default:
    driver: bridge
