global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus_inforadar:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter_inforadar:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor_inforadar:8080']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_inforadar:9104']

  - job_name: 'inforadar_ui'
    static_configs:
      - targets: [ 'inforadar_ui:5000' ]
