apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus_inforadar:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki_inforadar:3100
    jsonData:
      derivedFields:
        - datasourceUid: Prometheus
          matcherRegex: ".*"
